[package]
name = "arctix-drop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
tokio = "1"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
